window.LINUX_ALARM_QUESTIONS = [
  {
    id: "field-find-recent-logs",
    category: "field",
    level: "現場頻出",
    type: "command",
    text: "/var/log 配下から 24 時間以内に更新された通常ファイルを探すコマンドはどれか。パス、種類、更新日時条件を含めて入力する。",
    answers: ["find /var/log -type f -mtime -1"],
    match: "orderedTokens",
    hint: "find は検索開始パス、条件、条件の順で書ける。mtime は 24 時間単位。",
  },
  {
    id: "field-port-listen",
    category: "field",
    level: "現場頻出",
    type: "single",
    text: "TCP の LISTEN ポートとプロセスを確認するコマンドとして最も適切なものはどれか。",
    options: ["ss -lntp", "lsblk -fp", "ip route show table all", "journalctl --vacuum-time=7d"],
    answer: [0],
    hint: "ss は socket statistics。l は listening、n は名前解決なし、t は TCP、p は process。",
  },
  {
    id: "field-disk-usage",
    category: "field",
    level: "現場頻出",
    type: "single",
    text: "ファイルシステムごとのディスク使用量を人間が読みやすい単位で確認するコマンドはどれか。",
    options: ["du -sh /", "df -h", "free -m", "lsblk -o NAME,SIZE"],
    answer: [1],
    hint: "df は filesystem 単位、du はディレクトリやファイル単位。",
  },
  {
    id: "field-top-memory",
    category: "field",
    level: "現場頻出",
    type: "multi",
    text: "メモリ使用状況の確認に直接使いやすいコマンドをすべて選べ。",
    options: ["free -h", "vmstat 1", "uname -r", "cat /proc/meminfo"],
    answer: [0, 1, 3],
    hint: "カーネルバージョンを表示するコマンドはメモリ確認ではない。",
  },
  {
    id: "field-journal-since",
    category: "field",
    level: "現場頻出",
    type: "command",
    text: "systemd journal から今日のログだけを表示するコマンドを入力する。",
    answers: ["journalctl --since today"],
    match: "orderedTokens",
    hint: "journalctl は --since に today や時刻を渡せる。",
  },
  {
    id: "field-grep-context",
    category: "field",
    level: "現場頻出",
    type: "single",
    text: "error を含む行の前後 3 行も合わせて app.log から表示するコマンドはどれか。",
    options: ["grep -C 3 error app.log", "grep -n 3 error app.log", "grep -v 3 error app.log", "grep -m 3 error app.log"],
    answer: [0],
    hint: "-C は context。前だけなら -B、後だけなら -A。",
  },
  {
    id: "field-tail-follow",
    category: "field",
    level: "現場頻出",
    type: "single",
    text: "ログファイルの末尾を追跡表示するコマンドはどれか。",
    options: ["tail -f /var/log/syslog", "head -f /var/log/syslog", "less -S /var/log/syslog", "watch -f /var/log/syslog"],
    answer: [0],
    hint: "tail は末尾。f は follow。",
  },
  {
    id: "field-process-tree",
    category: "field",
    level: "現場頻出",
    type: "multi",
    text: "プロセスの親子関係やツリー表示に使えるものをすべて選べ。",
    options: ["pstree -ap", "ps axjf", "ps aux --sort=-%mem", "systemctl list-timers"],
    answer: [0, 1],
    hint: "ps の j/f 系オプションは job format や forest 表示に関係する。",
  },
  {
    id: "lpic1-permission-numeric",
    category: "lpic1",
    level: "LPIC-1",
    type: "single",
    text: "所有者 rwx、グループ r-x、その他 r-- にする数値モードはどれか。",
    options: ["754", "744", "764", "755"],
    answer: [0],
    hint: "r=4、w=2、x=1 を足す。",
  },
  {
    id: "lpic1-change-owner",
    category: "lpic1",
    level: "LPIC-1",
    type: "command",
    text: "file.txt の所有者を alice、グループを developers に変更するコマンドを入力する。",
    answers: ["chown alice:developers file.txt"],
    match: "orderedTokens",
    hint: "chown は user:group の形式を取れる。",
  },
  {
    id: "lpic1-tar-gzip",
    category: "lpic1",
    level: "LPIC-1",
    type: "single",
    text: "dir を gzip 圧縮 tar アーカイブ backup.tar.gz として作成するコマンドはどれか。",
    options: ["tar czf backup.tar.gz dir", "tar xzf backup.tar.gz dir", "gzip -x backup.tar.gz dir", "cpio -id backup.tar.gz dir"],
    answer: [0],
    hint: "tar の c は create、z は gzip、f は file。",
  },
  {
    id: "lpic1-runlevel-target",
    category: "lpic1",
    level: "LPIC-1",
    type: "single",
    text: "systemd で従来のランレベル 3 におおむね相当するターゲットはどれか。",
    options: ["multi-user.target", "graphical.target", "rescue.target", "poweroff.target"],
    answer: [0],
    hint: "GUI なしのマルチユーザー環境を表す名前。",
  },
  {
    id: "lpic1-package-debian",
    category: "lpic1",
    level: "LPIC-1",
    type: "multi",
    text: "Debian 系でパッケージ操作に使うコマンドをすべて選べ。",
    options: ["apt", "dpkg", "rpm", "dnf"],
    answer: [0, 1],
    hint: "rpm と dnf は RPM 系でよく使う。",
  },
  {
    id: "lpic1-fstab-fields",
    category: "lpic1",
    level: "LPIC-1",
    type: "single",
    text: "/etc/fstab の第 3 フィールドが表すものはどれか。",
    options: ["ファイルシステムタイプ", "マウントポイント", "dump 対象", "fsck 順序"],
    answer: [0],
    hint: "device、mount point の次に来る項目。",
  },
  {
    id: "lpic1-grep-invert",
    category: "lpic1",
    level: "LPIC-1",
    type: "command",
    text: "config.conf から # で始まる行以外を表示する grep コマンドを入力する。",
    answers: ["grep -v '^#' config.conf", "grep -v ^# config.conf"],
    match: "normalized",
    hint: "-v はマッチしない行を表示する。行頭は ^。",
  },
  {
    id: "lpic1-nice",
    category: "lpic1",
    level: "LPIC-1",
    type: "single",
    text: "既存プロセスの nice 値を変更するコマンドはどれか。",
    options: ["renice", "nice", "chrt", "ionice"],
    answer: [0],
    hint: "nice は起動時、renice は実行中プロセス。",
  },
  {
    id: "lpic2-ip-forward",
    category: "lpic2",
    level: "LPIC-2",
    type: "command",
    text: "IPv4 フォワーディングの現在値を sysctl で確認するコマンドを入力する。",
    answers: ["sysctl net.ipv4.ip_forward"],
    match: "orderedTokens",
    hint: "カーネルパラメータは sysctl で key を指定して確認できる。",
  },
  {
    id: "lpic2-nft-list",
    category: "lpic2",
    level: "LPIC-2",
    type: "single",
    text: "nftables の現在のルールセットを表示するコマンドはどれか。",
    options: ["nft list ruleset", "iptables-save -nft", "firewall-cmd --runtime-to-permanent", "ip rule list nft"],
    answer: [0],
    hint: "nft コマンドは list ruleset で全体を表示できる。",
  },
  {
    id: "lpic2-lvm-extend",
    category: "lpic2",
    level: "LPIC-2",
    type: "multi",
    text: "LVM 論理ボリューム拡張時に関係するコマンドをすべて選べ。",
    options: ["lvextend", "resize2fs", "xfs_growfs", "mkfs.ext4"],
    answer: [0, 1, 2],
    hint: "ファイルシステム作成は既存データを壊す操作。拡張とは別。",
  },
  {
    id: "lpic2-bind-zone-check",
    category: "lpic2",
    level: "LPIC-2",
    type: "single",
    text: "BIND のゾーンファイル構文を確認するコマンドはどれか。",
    options: ["named-checkzone", "named-checkconf", "dig +trace", "rndc reload"],
    answer: [0],
    hint: "設定ファイル全体は named-checkconf、ゾーンファイルは named-checkzone。",
  },
  {
    id: "lpic2-apache-vhost",
    category: "lpic2",
    level: "LPIC-2",
    type: "single",
    text: "Apache httpd の有効な VirtualHost 設定を一覧しやすいコマンドはどれか。",
    options: ["apachectl -S", "apachectl -M", "apachectl -t -D DUMP_MODULES", "httpd -k graceful"],
    answer: [0],
    hint: "-S は VirtualHost と設定解決の確認に使う。",
  },
  {
    id: "lpic2-raid-status",
    category: "lpic2",
    level: "LPIC-2",
    type: "command",
    text: "Linux software RAID の状態を /proc から確認するコマンドを入力する。",
    answers: ["cat /proc/mdstat"],
    match: "orderedTokens",
    hint: "md デバイスの状態は /proc/mdstat に出る。",
  },
  {
    id: "lpic2-postfix-queue",
    category: "lpic2",
    level: "LPIC-2",
    type: "single",
    text: "Postfix のメールキューを表示するコマンドはどれか。",
    options: ["postqueue -p", "postconf -n", "newaliases -p", "mailq -d"],
    answer: [0],
    hint: "mailq でも表示できるが、選択肢では postqueue の表示オプションを選ぶ。",
  },
  {
    id: "deep-lsof-deleted",
    category: "deep",
    level: "マニアック",
    type: "single",
    text: "削除済みだがプロセスが掴んでいるファイルを調べる定番の手がかりはどれか。",
    options: ["lsof | grep deleted", "find / -empty -delete", "sync; echo 3 > /proc/sys/vm/drop_caches", "stat --deleted /proc/*/fd"],
    answer: [0],
    hint: "ディスク空き容量が戻らないときに lsof の deleted 表示を見ることがある。",
  },
  {
    id: "deep-ip-netns",
    category: "deep",
    level: "マニアック",
    type: "command",
    text: "network namespace の一覧を表示する ip コマンドを入力する。",
    answers: ["ip netns list"],
    match: "orderedTokens",
    hint: "ip コマンドのサブコマンドに netns がある。",
  },
  {
    id: "deep-strace-open",
    category: "deep",
    level: "マニアック",
    type: "single",
    text: "PID 1234 に attach して open 系システムコールだけを追う strace コマンドはどれか。",
    options: ["strace -p 1234 -e trace=open,openat", "strace 1234 --open-only", "ltrace -p 1234 -e openat", "perf trace -F open 1234"],
    answer: [0],
    hint: "strace は -p で PID に attach、-e trace= で対象 syscall を絞る。",
  },
  {
    id: "deep-systemd-critical",
    category: "deep",
    level: "マニアック",
    type: "multi",
    text: "systemd の起動時間分析に使えるコマンドをすべて選べ。",
    options: ["systemd-analyze blame", "systemd-analyze critical-chain", "systemctl isolate rescue.target", "journalctl --list-boots"],
    answer: [0, 1, 3],
    hint: "isolate はターゲット切り替えで、分析表示ではない。",
  },
  {
    id: "deep-sed-inplace",
    category: "deep",
    level: "マニアック",
    type: "command",
    text: "file.conf 内の old を new にすべて置換し、ファイルを直接更新する sed コマンドを入力する。",
    answers: ["sed -i 's/old/new/g' file.conf", "sed -i s/old/new/g file.conf"],
    match: "normalized",
    hint: "-i は in-place。置換は s/old/new/g。",
  },
  {
    id: "deep-awk-first-field",
    category: "deep",
    level: "マニアック",
    type: "single",
    text: "access.log の第 1 フィールドだけを出力する awk はどれか。",
    options: ["awk '{print $1}' access.log", "awk '{print #1}' access.log", "awk '$1 print' access.log", "awk 'print {1}' access.log"],
    answer: [0],
    hint: "awk のフィールドは $1、$2 のように参照する。",
  },
  {
    id: "deep-tcpdump",
    category: "deep",
    level: "マニアック",
    type: "single",
    text: "eth0 の TCP 443 番ポート通信を名前解決せずに表示する tcpdump コマンドはどれか。",
    options: ["tcpdump -i eth0 -nn tcp port 443", "tcpdump eth0 --no-dns tcp 443", "ss -i eth0 -nn tcp port 443", "ip monitor eth0 tcp dport 443"],
    answer: [0],
    hint: "tcpdump は -i でインターフェース、-nn で名前解決を抑止する。",
  },
  {
    id: "deep-find-perm",
    category: "deep",
    level: "マニアック",
    type: "command",
    text: "カレントディレクトリ配下から SUID が設定された通常ファイルを探す find コマンドを入力する。",
    answers: ["find . -type f -perm -4000"],
    match: "orderedTokens",
    hint: "SUID は 4000。find の -perm -MODE は該当ビットがすべて立っているもの。",
  },
];
